apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdp-backend-dev-deploy
  namespace: gdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdp-backend-dev-deploy
  template:
    metadata:
      labels:
        app: gdp-backend-dev-deploy
    spec:
      imagePullSecrets:
        - name: harbor-image-pull-secret
      containers:
        - name: gdp-backend
          image: harbor.stdtrinfra.com/gdp-backend/gdp-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: gdp-backend-secret
