apiVersion: v1
kind: Service
metadata:
  name: gdp-backend-dev-service
  namespace: gdp
spec:
  selector:
    pod: gdp-backend-dev-deploy
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: ClusterIP