apiVersion: v1
kind: Service
metadata:
  name: gdp-backend-dev-service
  namespace: gdp
spec:
  selector:
    app: gdp-backend-dev-deploy
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
  type: ClusterIP