apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdp-backend-deploy
  namespace: gdp
  labels:
    app: gdp-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: gdp-backend-deploy
  template:
    metadata:
      labels:
        pod: gdp-backend-deploy
    spec:
      imagePullSecrets:
        - name: harbor-image-pull-secret
      containers:
        - name: gdp-backend
          image: harbor.stdtrinfra.com/gdp-backend/gdp-backend:latest
          ports:
            - containerPort: 8443
          envFrom:
            - secretRef:
                name: gdp-backend-secret
