apiVersion: v1
kind: Service
metadata:
  name: gdp-backend-service
  namespace: gdp
spec:
  selector:
    app: gdp-backend-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP