apiVersion: v1
kind: Service
metadata:
  name: gdp-backend-service
  namespace: gdp
spec:
  selector:
    pod: gdp-backend-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP